### ISSUE TITLE
aws-lite/client may not discover all plugins

### ISSUE THREAD

**Issue by tbeseda** [architect/aws-lite#94] opened 2024-02-04 23:12 UTC
### Describe the issue

When the dependency graph is broad and many packages use the same `@aws-lite/*` plugins, one instance may not pick up all installed plugins.
This is a side effect of Node.js dependency resolution algo and the dedupe strategy.

### Expected behavior

Loading `@aws-lite/client` should include all plugins specified in that package's manifest. Even when the plugins are deduped across modules.

### Steps to reproduce

It's hard to give discreet steps to repro

Here's some terminal output running Arc v11@RC-5 when I deploy a large Arc + Enhance application:

```
> arc deploy --production

         App ⌁ tbeseda-com
      Region ⌁ us-east-1
     Profile ⌁ Not configured / default
     Version ⌁ Architect 11.0.0-RC.5
         cwd ⌁ /Users/tbeseda/dev/tbeseda/tbeseda-com

deploy failed! Cannot read properties of undefined (reading 'DescribeStackResources')
TypeError: Cannot read properties of undefined (reading 'DescribeStackResources')
    at getResources (~/tbeseda-com/node_modules/@architect/deploy/src/sam/compat/index.js:77:22)
    at Array.getApiType (~/tbeseda-com/node_modules/@architect/deploy/src/sam/compat/index.js:19:9)
    at runSeries (~/tbeseda-com/node_modules/run-series/index.js:23:33)
    at compat (~/tbeseda-com/node_modules/@architect/deploy/src/sam/compat/index.js:11:3)
    at compatCheck (~/tbeseda-com/node_modules/@architect/deploy/src/sam/index.js:86:7)
    at each (~/tbeseda-com/node_modules/run-waterfall/index.js:22:22)
    at Array.createFiles (~/tbeseda-com/node_modules/@architect/deploy/src/sam/index.js:81:12)
    at runWaterfall (~/tbeseda-com/node_modules/run-waterfall/index.js:27:13)
    at samDeploy (~/tbeseda-com/node_modules/@architect/deploy/src/sam/index.js:73:3)
    at ~/tbeseda-com/node_modules/@architect/deploy/index.js:67:11
```

In this case, `aws.cloudformation` is undefined in `@architect/deploy`.

But `@aws-lite/cloudformation` is definitely in `@architect/deploy`'s `package.json`. However, when `npm install` ran it deduped the `cloudformation` plugin so it doesn't actually live in the `node_modules` in the `@architect/deploy` directory in my project's `node_modules`.

If I patch `{ ... plugins: ["@aws-lite/cloudformation"]}` into the `@aws-lite/client` in `deploy`, I get another error related to `ssm` being undefined.

So I used `npm ls` to see where `@aws-lite/ssm` is:  
(so you don't need to parse this list, `smm` is in `@architect/functions` and listed as _deduped_ in `@architect/deploy`)

```
npm ls @aws-lite/ssm
tbeseda-com@2.0.0 /Users/tbeseda/dev/tbeseda/tbeseda-com
├─┬ @architect/architect@11.0.0-RC.5
│ ├─┬ @architect/create@5.0.0
│ │ └─┬ @architect/inventory@4.0.1
│ │   └── @aws-lite/ssm@0.2.2 deduped
│ ├─┬ @architect/deploy@5.0.0
│ │ ├─┬ @architect/inventory@4.0.1
│ │ │ └── @aws-lite/ssm@0.2.2 deduped
│ │ ├─┬ @architect/package@9.0.0
│ │ │ └─┬ @architect/inventory@4.0.1
│ │ │   └── @aws-lite/ssm@0.2.2 deduped
│ │ └── @aws-lite/ssm@0.2.2 deduped
│ ├─┬ @architect/destroy@4.0.0
│ │ ├─┬ @architect/inventory@4.0.1
│ │ │ └── @aws-lite/ssm@0.2.2 deduped
│ │ └── @aws-lite/ssm@0.2.2 deduped
│ ├─┬ @architect/env@4.0.0
│ │ ├─┬ @architect/inventory@4.0.1
│ │ │ └── @aws-lite/ssm@0.2.2 deduped
│ │ └── @aws-lite/ssm@0.2.2 deduped
│ ├─┬ @architect/hydrate@4.0.0
│ │ └─┬ @architect/inventory@4.0.1
│ │   └── @aws-lite/ssm@0.2.2 deduped
│ ├─┬ @architect/inventory@4.0.1
│ │ └── @aws-lite/ssm@0.2.2 deduped
│ ├─┬ @architect/logs@5.0.0
│ │ └─┬ @architect/inventory@4.0.1
│ │   └── @aws-lite/ssm@0.2.2 deduped
│ └─┬ @architect/sandbox@6.0.0
│   └─┬ @architect/inventory@4.0.1
│     └── @aws-lite/ssm@0.2.2 deduped
├─┬ @architect/functions@8.0.0
│ └── @aws-lite/ssm@0.2.2
└─┬ @enhance/arc-plugin-enhance@9.4.5
  └─┬ @begin/data@5.0.0
    └── @aws-lite/ssm@0.2.2 deduped
```

This is why `@architect/deploy`'s instance of `@aws-lite/client` never loads any plugins :|

### Platform / version

- OS + version: macOS
- Node version: v18 and v20
- Package manager version: npm v10.2.3

### How urgent do you feel this bug is?

P1

### Additional context

Looks like the `@aws-lite/client`'s `clientFactory` reads the parent package's `node_modules`

```js
let mods = await readdir(nodeModulesDir)
```

Then it searches for official `^@aws-lite/` plugins, 3rd party, and excludes `-types$` to load.

Maybe reading the parent's `package.json`'s `"dependencies": {...}` in a similar way would be safer?

**Comment by ryanblock** [comment] 2024-02-05 04:11
I've seen this come up from time to time, but it hasn't been super common, and it's not been reproducible because, as you said, it's related to how npm (or other package managers) resolve and flatten the dependency tree. In the case above, that dep tree is all kinds of messed up and duplicated, which can thwart the current plugin autoloading process.

Re, this bit:
> If I patch { ... plugins: ["@aws-lite/cloudformation"]} into the @aws-lite/client in deploy, I get another error related to ssm being undefined.
That is to be expected; you'd have to specify all necessary plugins for that approach to work; only specifying one will satisfy the requirement of just that single plugin.

In https://github.com/architect/aws-lite/pull/95 I've updated the autoloading process to do the following:
- First: scan the installed node_modules dir of the parent process, if present (new)
  - This should hopefully account for key cases and, importantly, what happens when plugins are installed as subdependencies; however, this will not and cannot account for plugins installed as deeply nested subdependencies
- Second (if nothing found above): scan the installed node_modules of the dir where `@aws-lite/client` resolves, if present (new)
  - This used to be the primary means of approaching the problem, and is still valid, but obviously could not / cannot account for plugins installed as nested subdependencies of other dependencies
- Third (if still nothing found): attempt to locate the project's root package.json file (via `process.cwd()`) and see if the `dependencies` property contains any plugins
  - This is a last resort, as plugins installed as dependencies would not load here; for example, if `@aws-lite/client` is running via `@architect/functions`, no `@aws-lite/*` dependencies will be in package.json, only `@architect/functions`

**Comment by tbeseda** [comment] 2024-02-05 04:26
Right on. I saw the patch, applied it to my specific project, and was able to deploy without error.

IMO this approach is a "good effort search" without totally blocking while you crawl every corner of the disk.

And if I read it right, a consumer could alway specify the plugins array in the config in order to skip the search and eek out some perf.

Re:
> > I get another error related to ssm being undefined.

> That is to be expected; you'd have to specify all necessary plugins for that approach to work; only specifying one will satisfy the requirement of just that single plugin.

Yes, I just didn't want to add one by one until it worked so I quit there and started printing dependency trees :)

Thanks for looking into it 👍

**Closed** 2024-02-05 16:30 UTC
Labels: bug
