### ISSUE TITLE
Intermittent InvalidSignatureException with DynamoDB

### ISSUE THREAD

**Issue by alexbepple** [architect/aws-lite#127] opened 2024-05-14 10:40 UTC
### Describe the issue

Intermittently we see requests to DynamoDB fail with `InvalidSignatureException`:

```
 InvalidSignatureException: @aws-lite/client: DynamoDB.Query: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
    at errorHandler (/var/task/node_modules/@aws-lite/client/src/error.js:13:46)
    at Query (/var/task/node_modules/@aws-lite/client/src/client-factory.js:187:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///var/task/index.mjs:14:20
    at async lambda (/var/task/node_modules/@architect/functions/src/http/index.js:37:22) 
```

### Expected behavior

No `InvalidSignatureException`. ;-)

### Steps to reproduce

Difficult to reproduce.
We have only been able to _provoke_ the problem by creating some load.
However, we have seen instances of this error with hardly any load (single user).

### Platform / version

- Lambda runtime: nodejs20.x
- @architect/functions@8.1.0
- @aws-lite/client@0.20.0
- @aws-lite/dynamodb@0.3.4

### How urgent do you feel this bug is?

4/5

We reverted to `@architect/functions@7.x` (aws-sdk) and won’t use aws-lite until this is solved.

### Additional context

1. The signing of AWS requests seems to happen in `@aws-lite/client`. This suggests that other AWS services might be affected, too. However, so far, we have only observed the exception when using DynamoDB and, more specifically, Query. To be fair, this reflects our usage of AWS services, so maybe selection bias.

2. In most cases, the InvalidSignatureException occurred on the first and only retry, after the 1st call did not seem to receive any response at all. See screenshots. However, we consider this circumstance secondary, as we have cases of the InvalidSignatureException occurring on the first try.

Call 1:
<img width="500" alt="InvalidSignatureException mit retry call 1" src="https://github.com/architect/aws-lite/assets/159355/5f8ee399-2634-49f6-9291-d314b2093a84">

Call 2:
<img width="500" alt="InvalidSignatureException mit retry call 2" src="https://github.com/architect/aws-lite/assets/159355/e830d387-9b83-4a18-a78f-d3df6cd9dee0">

3. This old bug in aws-sdk-go seems related: https://github.com/aws/aws-sdk-go/issues/2598#issuecomment-1673674510

**Comment by ryanblock** [comment] 2024-05-14 15:20
@alexbepple thanks! I think we just need to add this to our retry heuristics – `InvalidSignatureException` is classified as a retryable "clock skew error" by AWS SDKs (see: [v3](https://github.com/smithy-lang/smithy-typescript/blob/c03ce2aa4d336906a8b89ff8078cad10eddadf28/packages/service-error-classification/src/constants.ts#L10), [v2](https://github.com/aws/aws-sdk-js/blob/aa6049093165b84eac975aa50c3a44e23cbfe4af/lib/service.js#L596)). I think I've got enough here to bang out a patch, please stand by!

**Comment by ryanblock** [comment] 2024-05-14 18:07
Should now be fixed in v0.21.3 (also be released via `@architect/functions` v8.1.2). Thank you for the excellent bug report!

**Comment by alexbepple** [comment] 2024-05-14 20:24
Thank you for the very quick fix. Will give it a try tomorrow.

**Comment by alexbepple** [comment] 2024-05-15 08:49
Looking good. Thank you, @ryanblock.

**Comment by alexbepple** [comment] 2024-05-15 12:01
@ryanblock That was a bit premature. Mere hours after deploying this in production, we observed a variation of the problem: the `InvalidSignatureException` persisted across all retries.

Let me reiterate: your fix seems to have substantially improved the situation. With the load numbers we used yesterday to provoke the problem, we had no problems at all today. However, by increasing the load numbers further we have been able to provoke the variation of the problem.

We now know for sure that the problem is not restricted to DynamoDB, but also affects other services, e.g. SSM.

Through further experimentation we suspect that the problem is somehow related to cold starts. We used k6 for load testing. Increasing iterations alone did nothing. Only by massively increasing VUs (parellelization) have we been able to provoke the error. Repeating the run is fine again.

Combining the fact that your fix did something good and that all retries fail in the variation we are dealing with now leads us to suspect that the retry strategy is successful sometimes, but not always. Does this point you in a useful direction, @ryanblock? 

6th attempt with DynamoDB:
<img width="500" alt="Screenshot 2024-05-15 at 13 09 13" src="https://github.com/architect/aws-lite/assets/159355/b1da2f64-9b14-4d61-921f-ddaf1d611b40">

Timeline of the attempts to use SSM:
<img width="500" alt="Screenshot 2024-05-15 at 13 57 47" src="https://github.com/architect/aws-lite/assets/159355/315ea691-5c4d-42b9-b8b1-3012560fa364">

**Comment by alexbepple** [comment] 2024-05-15 12:04
Looking up your links, we noticed this comment: «These errors are retryable, assuming the SDK has enabled clock skew correction.» (https://github.com/smithy-lang/smithy-typescript/blob/c03ce2aa4d336906a8b89ff8078cad10eddadf28/packages/service-error-classification/src/constants.ts#L10)

Does `aws-lite` maybe need to do more than retry when the problem occurs?

**Comment by ryanblock** [comment] 2024-05-15 14:40
Your environment is Lambda, so I'm assuming you should not need a clock skew correction for the signature v4 signing here. Lambda can be assumed to be UTC synced. Your request headers also confirm this; in your screenshot the request is made at `20240515T092934Z`, and the response is dated `20240515T092935Z` (which should be well within the valid window).

By default aws-lite retries 5 times (on retryable errors, such as `InvalidSignatureException`) before failing. aws-lite also generates a fresh signature for each retry request. Here's the order of execution:

- Incoming API request is sent to the request module: https://github.com/architect/aws-lite/blob/main/src/request/index.js#L120
- Retries are calculated, and the API request is (maybe) called: https://github.com/architect/aws-lite/blob/main/src/request/request.js#L34
- Called request is signed and sent: https://github.com/architect/aws-lite/blob/main/src/request/request.js#L74

I have yet to encounter this error in the AWS AZs that we use (`us-*`), and over the years I've seen a lot of wonky, subtly different behavior across AWS regions, especially between continents. I'm not saying it's not aws-lite, just that perhaps we haven't yet figured out the specific, unique `eu-*` heuristic to guard against here yet.

Some things I'd kindly ask you try to see what more we can learn:

- Can you deploy this app to a `us-*` AZ and run it from there to see if the issue reproduces?
- Can you reproduce this issue in a minimal repro repo?
- Can you add the `AWS_LITE_DEBUG` env var to the environment that's failing for you right now, and send me some logged failures (privately, so as to include all headers) on [Discord](https://discord.com/invite/y5A2eTsCRX)?

Thanks!

**Comment by ryanblock** [comment] 2024-05-15 15:29
Thanks! In the mean time I will keep working on it from my end. This is a p0 to us right now.

**Comment by alexbepple** [comment] 2024-05-16 16:23
We have not been able to provoke the issue with a greenfield barebones Architect app with aws-lite that we deployed in eu-central-1. This is both good and bad news. It is good news for aws-lite in the sense that so far nothing points to a further problem with aws-lite. But for us this is rather bad news, as we now have a mysterious problem that is even harder to track down. Still, I hope that you remain interested in the issue. At face value, this looks like an aws-lite problem. ;-)

I will skip deployment to other AWS regions for now, as the relevant difference seems to be between the greenfield barebones app and our own app. We will try to find the relevant delta on our side.

Meanwhile, I am sending you the logs of a failure with `AWS_LITE_DEBUG` via Discord. Hopefully you can gleam something from them.

**Comment by ryanblock** [comment] 2024-05-16 19:49
I haven't given up on this, and I agree at face value it looks like an aws-lite problem, but I'm beginning to suspect aws-lite may be a red herring. (I'm not certain yet at all, though!)

Here's a repo I created to attempt to reproduce the issue, based in part on the logs you sent over. https://github.com/ryanblock/aws-lite-127-repro tl;dr - so far I can't reproduce.

In the more detailed logs you sent, I observed you almost immediately got a `ThrottlingException` by your 4th page of SSM results in your staging environment. This then resulted in a `InvalidSignatureException` upon the next retry, and SSM then kept responding with additional `InvalidSignatureException` errors until all aws-lite retries were exhausted. Related, I observed that in your logs, the signatures changed each time (`Signature=7ae47c28...`, `Signature=009c28c2...`, `Signature=36e4982d...`, `Signature=884ac20f...`), indicating that each subsequent request was likely updated to the new time and correctly signed (see https://github.com/mhart/aws4/blob/master/aws4.js#L205).

In my repro repo attempt: after deploying the app and loading `get /`, the handler makes 100 attempts to load the app's >50 SSM params, thereby causing 6 pagination requests per invocation (read: 600+ SSM hits in a few seconds). In my testing (also in `eu-central-1`), the signing process seemed to be operating normally (as was apparently the case in your app), but unlike your app I was never able to get a `ThrottlingException` or `InvalidSignatureException`. Given that you only made 4 SSM requests in your staging environment before hitting errors, I find this pretty confounding.

Currently I'm a bit at a loss here.

**Comment by ryanblock** [comment] 2024-05-17 02:06
A quick update: to further aid debugging, I pushed v0.21.4 (and bumped `@architect/functions`) which will now output a bit more detailed logging, especially during paginated / retried requests.

**Comment by alexbepple** [comment] 2024-05-17 07:34
> In my repro repo attempt: after deploying the app and loading `get /`, the handler makes 100 attempts to load the app's >50 SSM params, thereby causing 6 pagination requests per invocation (read: 600+ SSM hits in a few seconds). In my testing (also in `eu-central-1`), the signing process seemed to be operating normally (as was apparently the case in your app), but unlike your app I was never able to get a `ThrottlingException` or `InvalidSignatureException`. Given that you only made 4 SSM requests in your staging environment before hitting errors, I find this pretty confounding.

In order to provoke the ISE, I made 200 concurrent requests to the same cold Lambda, of which a couple failed. I only sent you the logs for one of the failures. The concurrency might explain the `ThrottlingException`.

**Comment by alexbepple** [comment] 2024-05-17 07:58
> I'm beginning to suspect aws-lite may be a red herring.

As things stand, I wholeheartedly agree.

**Comment by alexbepple** [comment] 2024-05-17 21:00
We have zeroed in on the issue, we believe.

It turns out that `InvalidSignatureException` is indeed a red herring. We use Lumigo for observability and it seems to somehow turn a `ThrottlingException` into a `InvalidSignatureException`. I will send you the logs for the same kind of failure with and without Lumigo. – I am still a bit baffled by this and unsure how exactly it is happening.
The Lumigo package in case you are very curious: https://www.npmjs.com/package/@lumigo/tracer

So, once we eliminate this smoke and mirrors, we are left with a cascade of `ThrottlingException`s. Since we have never seen this behavior before aws-lite, i.e. never with aws-sdk, I can only hypothesize that aws-lite’s retry strategy is more aggressive than that of aws-sdk. Do you agree with this conclusion? Would you consider amending the retry strategy in a manner that makes `ThrottlingException` less likely on retry. I perfectly understand that no retry strategy can avoid it entirely.

Please find the repro repo at https://github.com/heartstocks/aws-lite-InvalidSignatureException. The readme also contains the example call for `k6` with many concurrent requests. _Essential:_ have at least 11 SSM params that would be loaded by `arc.services()` in order to make two SSM calls and thus cause throttling with 200 concurrent requests, better yet 21 SSM params (three SSM calls).

**Comment by ryanblock** [comment] 2024-05-18 21:06
This is great information to have on hand, thank you! I too don't have any idea how that's even possible, unless Lumigo is somehow mutating the credential env vars in the Lambda environment? I don't see anything immediately in their tracer project that would do such a thing, but I'd definitely be curious to hear what's up if you raised the issue with them.

As for AWS API retries, there are two key vectors of note: a) how long of a delay before the next retry, and b) many total retries are made. By default, I believe we retry more times than AWS (our [5 retries](https://github.com/architect/aws-lite/blob/main/src/request/request.js#L25) vs their [3 retries](https://github.com/smithy-lang/smithy-typescript/blob/be063c689c889806cb65d9aa4802ac9bee9655b4/packages/util-retry/src/config.ts#L15)), so I don't think it's a matter of the library giving up first.

I suspect the reason you are probably seeing this `ThrottlingException` in aws-lite where you may not have seen it previously with the AWS SDK relates to how backoff time is computed. We conform to AWS's generally recommended exponential backoff with jitter ([background here](https://github.com/architect/aws-lite/issues/106), and [implementation here](https://github.com/architect/aws-lite/blame/main/src/request/request.js#L303)), and it appears we also happen to implement the same algorithm (pseudocode): `Math.random() * (attempts^2) * delaybase`.

The chief difference is AWS SDK's `delaybase` is `100`, whereas ours is `50`. A higher value there will result in greater likelihood of increased latency between requests; if the retry requests are more spaced out, there's an increased chance that the throttling will be alleviated upon the next request. The flip side to that is requests which are invisibly retried under the hood will also take longer to complete.

I think it's probably worth increasing our `delaybase` to match AWS's for the sake of behavioral symmetry, which I've done in v0.21.5 (and released to `@architect/functions`). Given the above, I'm thinking it's safe to close this issue; as of the latest version, I believe the only difference between aws-lite and AWS SDK defaults is that we retry more times out of the box. But I'll leave that to you for now, @alexbepple!

**Comment by ryanblock** [comment] 2024-05-21 04:25
When researching a bug that appears to have inflicted a number of people, including @jessehattabaugh, @w5mix, and possibly @filmaj (and is possibly related to #115), I discovered our AWS signing library `aws4` mutates its arguments. ([Related issue](https://github.com/mhart/aws4/issues/164).) In the case of aws-lite plugins, that can plugin logic that passes references can wind up with inadvertently mutated data across requests, leading to a variety of unpredictable behavior. I've [worked around this](https://github.com/architect/aws-lite/commit/42c1bab29f134fe36d100c92dd0bd9bcaf72a2b2) in v0.21.6 (and the latest `@architect/functions`).

**Closed** 2024-05-22 09:03 UTC
Labels: bug

**Comment by alexbepple** [comment] 2024-05-22 09:36
@ryanblock Using the [repro repo](https://github.com/heartstocks/aws-lite-InvalidSignatureException), we can no longer see any differences in behavior between aws-lite and aws-sdk. In fact, using the parameters for reproduction (>20 SSM parameters, 200 virtual users in load test) _both_ aws-lite and aws-sdk receive `ThrottlingException`s. One can easily relate this to the [default AWS rate limit of 40 tps for the Param Store](https://docs.aws.amazon.com/general/latest/gr/ssm.html).

On a side note, we could provoke the same behavior in both eu-central-1 & us-east-1. So no relevant difference there.

Most unfortunately, we still see mysterious `InvalidSignatureException` in production, which we do not have when we revert to aws-sdk. 😭 Since we do not properly understand what’s going on there, let’s keep this issue closed for now and we will come back, if and when we have something new.

**Comment by ryanblock** [comment] 2024-05-22 13:28
That's good, although I'm still vexed by the InvalidSignatureException you're getting with lite, but not AWS SDK. How often are you seeing it? Can we reproduce that without Lumigo?

**Comment by alexbepple** [comment] 2024-05-23 08:26
We are seeing the problem in production very occasionally, at most a few times a day, albeit with a very modest load.

Just as you suggested, we also decided that the way to get to the bottom of this is to disable Lumigo for a while. Let’s see …
